version: '3'
services:
  octopus:
    ports:
      - "8080:8080"
    environment:
      ADMIN_USERNAME: admin
      ADMIN_EMAIL: octopusguides@gmail.com
      ADMIN_PASSWORD: Password01!
      ACCEPT_EULA: !!str "Y"
      DB_CONNECTION_STRING: Server=mssql,1433;Database=Octopus;User Id=SA;Password=Password01!;ConnectRetryCount=6
      CONNSTRING: Server=mssql,1433;Database=Octopus;User Id=SA;Password=Password01!;ConnectRetryCount=6
      MASTER_KEY: 6EdU6IWsCtMEwk0kPKflQQ==
      ADMIN_API_KEY: API-ABCDEFGHIJKLMNOPQURTUVWXYZ12345
      OCTOPUS_SERVER_BASE64_LICENSE: "${OCTOPUS_SERVER_BASE64_LICENSE}"
    image: octopusdeploy/octopusdeploy
    depends_on:
      - mssql
  mssql:
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Password01!
      MSSQL_PID: Express
    image: mcr.microsoft.com/mssql/server